//
//  MainInteractor.swift
//  SHA
//
//  Created by Ilyá Belsky on 4/25/18.
//  Copyright (c) 2018 Ilyá Belsky. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol MainBusinessLogic {
    func fetchRecord(request: Main.FetchRecord.Request)
    func incrementFull(request: Main.IncrementFull.Request)
    func resetFull(request: Main.ResetFull.Request)
    func navigateBack(request: Main.NavigateBack.Request)
}

protocol MainDataStore {
    var records: [Record] { get }
    var currentRecord: Record! { get }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    var presenter: MainPresentationLogic?
    var worker = RecordsWorker(recordsStore: RecordsMemStore())
    
    var records: [Record] = [] {
        didSet {
            currentRecord = Record()
        }
    }
    var currentRecord: Record!
    
    // MARK: - Records
    
    func fetchRecord(request: Main.FetchRecord.Request) {
        worker.fetchRecords { records in
            self.records = records.count > 0 ? records : [Record()]
            let response = Main.FetchRecord.Response(record: self.currentRecord)
            self.presenter?.presentRecord(response: response)
        }
    }

    // MARK: - Counters
    
    func incrementFull(request: Main.IncrementFull.Request) {
        currentRecord.full += 1
        let response = Main.FetchRecord.Response(record: currentRecord)
        presenter?.presentRecord(response: response)
    }
    
    func resetFull(request: Main.ResetFull.Request) {
        currentRecord.full = 0
        let response = Main.FetchRecord.Response(record: currentRecord)
        presenter?.presentRecord(response: response)
    }
    
    // MARK: - Navigation
    
    func navigateBack(request: Main.NavigateBack.Request) {
        currentRecord.date = dayBefore(currentRecord.date)
        let response = Main.FetchRecord.Response(record: currentRecord)
        presenter?.presentRecord(response: response)
    }
    
    private func dayBefore(_ date: Date) -> Date {
        let oneDayInterval = 60 * 60 * 24 * 1.0
        return Date(timeInterval: -oneDayInterval, since: date)
    }
    
}
