//
//  MainViewController.swift
//  SHA
//
//  Created by Ilyá Belsky on 4/25/18.
//  Copyright (c) 2018 Ilyá Belsky. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainDisplayLogic: class {
    func displayRecord(viewModel: Main.FetchRecord.ViewModel)
    func displayShareView(viewModel: Main.Share.ViewModel)
}

class MainViewController: UIViewController, MainDisplayLogic {
    var interactor: MainBusinessLogic?
    var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?

    // MARK: - Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: - Setup

    private func setup() {
        let viewController = self
        let interactor = MainInteractor()
        let presenter = MainPresenter()
        let router = MainRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: - Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        fetchRecord()
    }

    // MARK: - Record

    @IBOutlet weak var dateLabel: UILabel!
    @IBOutlet weak var fullButton: UIButton!
    @IBOutlet weak var expressButton: UIButton!
    
    func fetchRecord() {
        let request = Main.FetchRecord.Request()
        interactor?.fetchRecord(request: request)
    }

    func displayRecord(viewModel: Main.FetchRecord.ViewModel) {
        dateLabel.text = viewModel.date
        fullButton.setTitle(viewModel.full, for: .normal)
        expressButton.setTitle(viewModel.express, for: .normal)
    }
    
    // MARK: - Counters
    
    @IBAction func fullButtonPressed(_ sender: Any) {
        incrementFull()
    }
    
    func incrementFull() {
        let request = Main.Increment.Request(counter: .full)
        interactor?.increment(request: request)
    }
    
    @IBAction func expressButtonPressed(_ sender: Any) {
        incrementExpress()
    }
    
    func incrementExpress() {
        let request = Main.Increment.Request(counter: .express)
        interactor?.increment(request: request)
    }
    
    @IBAction func fullButtonLongPressed(_ sender: UILongPressGestureRecognizer) {
        if sender.state == .began {
            resetFull()
        }
    }
    
    func resetFull() {
        let request = Main.Reset.Request(counter: .full)
        interactor?.reset(request: request)
    }
    
    @IBAction func expressButtonLongPressed(_ sender: UILongPressGestureRecognizer) {
        if sender.state == .began {
            resetExpress()
        }
    }
    
    func resetExpress() {
        let request = Main.Reset.Request(counter: .express)
        interactor?.reset(request: request)
    }
    


    // MARK: - Navigation
    
    @IBAction func prevButtonPressed(_ sender: Any) {
        navigatePrev()
    }
    
    @IBAction func nextButtonPressed(_ sender: Any) {
        navigateNext()
    }

    func navigatePrev() {
        let request = Main.Navigate.Request(direction: .prev)
        interactor?.navigate(request: request)
    }
    
    func navigateNext() {
        let request = Main.Navigate.Request(direction: .next)
        interactor?.navigate(request: request)
    }
    
    // MARK: - Share
    
    override func motionEnded(_ motion: UIEventSubtype, with event: UIEvent?) {
        if motion == .motionShake {
            shareReport()
        }
    }
    
    func shareReport() {
        let request = Main.Share.Request()
        interactor?.share(request: request)
    }
    
    func displayShareView(viewModel: Main.Share.ViewModel) {
        
    }
}
