//
//  MainInteractorTests.swift
//  SHA
//
//  Created by Ilyá Belsky on 4/25/18.
//  Copyright (c) 2018 Ilyá Belsky. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SHA
import XCTest

class MainInteractorTests: XCTestCase {
    // MARK: - Subject under test

    var sut: MainInteractor!

    // MARK: - Test lifecycle

    override func setUp() {
        super.setUp()
        setupMainInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: - Test setup

    func setupMainInteractor() {
        sut = MainInteractor()
    }

    // MARK: - Test doubles

    class MainPresentationLogicSpy: MainPresentationLogic {
        var presentRecordCalled = false
        var main_fetchRecord_response: Main.FetchRecord.Response?

        func presentRecord(response: Main.FetchRecord.Response) {
            presentRecordCalled = true
            main_fetchRecord_response = response
        }
    }
    
    class RecordsWorkerSpy: RecordsWorker {
        var fetchRecordCalled = false
        var incrementCalled = false
        var incrementArguments: (Record.Counters, RecordDate)?
        
        override func fetchRecord(for date: RecordDate, completionHandler: @escaping (Record) -> Void) {
            fetchRecordCalled = true
            completionHandler(Record())
        }
        
        override func increment(counter: Record.Counters, for date: RecordDate, completionHandler: @escaping (Record) -> Void) {
            incrementCalled = true
            incrementArguments = (counter, date)
        }

    }

    // MARK: - Tests
    // MARK: Fetch Record
    
    func testFetchRecordAsksWorkerToFetchRecord() {
        // Given
        let spy = RecordsWorkerSpy(recordsStore: RecordsMemStore())
        sut.worker = spy
        let request = Main.FetchRecord.Request()
        
        // When
        sut.fetchRecord(request: request)
        
        // Then
        XCTAssertTrue(spy.fetchRecordCalled, "fetchRecord(request:) should ask the worker to fetch the record")
    }

    func testFetchRecordAsksPresenterToFormatRecord() {
        // Given
        let presenterSpy = MainPresentationLogicSpy()
        sut.presenter = presenterSpy
        let request = Main.FetchRecord.Request()

        // When
        sut.fetchRecord(request: request)

        // Then
        XCTAssertTrue(presenterSpy.presentRecordCalled, "fetchRecord(request:) should ask the presenter to format the record")
        let record = presenterSpy.main_fetchRecord_response?.record
        XCTAssertEqual(record, Record())
    }
    
    // MARK: Increment

    func testIncrementAsksWorkerToIncrement() {
        // Given
        let workerSpy = RecordsWorkerSpy(recordsStore: RecordsMemStore())
        sut.worker = workerSpy

        let someDate = RecordDate(from: "2018-01-01")!
        sut.currentDate = someDate

        // When
        sut.increment(request: Main.Increment.Request(counter: .full))
        
        // Then
        XCTAssertTrue(workerSpy.incrementCalled, "increment(request:) should ask worker to increment")
        XCTAssertEqual(workerSpy.incrementArguments?.0, .full, "increment(request:) should ask worker with .full type")
        XCTAssertEqual(workerSpy.incrementArguments?.1, someDate, "increment(request:) should ask worker with .full type")
    }
    
    func testIncrementAsksPresenterToFormatRecord() {
        // Given
        let presenterSpy = MainPresentationLogicSpy()
        sut.presenter = presenterSpy
        let request = Main.Increment.Request(counter: .full)
        
        // When
        sut.increment(request: request)
        
        // Then
        XCTAssertTrue(presenterSpy.presentRecordCalled, "increment(request:) should ask the presenter to format a record")
        let record = presenterSpy.main_fetchRecord_response?.record
        XCTAssertEqual(record, Record(date: RecordDate(), full: 1, express: 0))
    }

    // MARK: Reset Full

//    func testResetFullAsksPresenterToFormatRecord() {
//        // Given
//        let presenterSpy = MainPresentationLogicSpy()
//        sut.presenter = presenterSpy
//        sut.currentRecord = Record(date: RecordDate(), full: 42, express: 0)
//        let request = Main.ResetFull.Request()
//
//        // When
//        sut.resetFull(request: request)
//
//        // Then
//        XCTAssertTrue(presenterSpy.presentRecordCalled, "resetFull(request:) should ask the presenter to format a record")
//        let record = presenterSpy.main_fetchRecord_response?.record
//        XCTAssertEqual(record, Record(date: Date(), full: 0, express: 0))
//    }

    // MARK: Navigate

    func testNavigatePrevAsksPresenterToFormatRecord() {
        // Given
        let presenterSpy = MainPresentationLogicSpy()
        sut.presenter = presenterSpy
        sut.currentDate = RecordDate(from: "2018-01-01")!
        let request = Main.Navigate.Request(direction: .prev)
        
        // When
        sut.navigate(request: request)
        
        // Then
        XCTAssertTrue(presenterSpy.presentRecordCalled, "navigate(request:) should ask the presenter to format a record")
        let record = presenterSpy.main_fetchRecord_response?.record
        XCTAssertEqual(record, Record(date: RecordDate(from: "2017-12-31")!, full: 0, express: 0))
    }
    
    func testNavigateNextAsksPresenterToFormatRecord() {
        // Given
        let presenterSpy = MainPresentationLogicSpy()
        sut.presenter = presenterSpy
        sut.currentDate = RecordDate(from: "2018-01-01")!
        let request = Main.Navigate.Request(direction: .next)
        
        // When
        sut.navigate(request: request)
        
        // Then
        XCTAssertTrue(presenterSpy.presentRecordCalled, "navigate(request:) should ask the presenter to format a record")
        let record = presenterSpy.main_fetchRecord_response?.record
        XCTAssertEqual(record, Record(date: RecordDate(from: "2018-01-02")!, full: 0, express: 0))
    }
    
}
