//
//  RecordsWorkerTests.swift
//  SHA
//
//  Created by Ilyá Belsky on 4/25/18.
//  Copyright (c) 2018 Ilyá Belsky. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SHA
import XCTest

class RecordsWorkerTests: XCTestCase {
    // MARK: - Subject under test

    var sut: RecordsWorker!

    // MARK: - Test lifecycle

    override func setUp() {
        super.setUp()
        setupWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: - Test setup

    func setupWorker() {
        sut = RecordsWorker(recordsStore: RecordsMemStoreSpy())
    }

    // MARK: - Test doubles
    
    class RecordsMemStoreSpy : RecordsMemStore {
        var fetchRecordsCalled = false
        
        override func fetchRecords(completionHandler: @escaping ([Record]) -> Void) {
            fetchRecordsCalled = true
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                completionHandler([])
            }
        }
    }

    // MARK: - Tests

    func testFetchRecord() {
        // Given
        let storeSpy = sut.recordsStore as! RecordsMemStoreSpy
        let expectRecord = expectation(description: "Wait for fetched record")

        // When
        sut.fetchRecord(for: Date(), completionHandler: { record in
            expectRecord.fulfill()
        })

        // Then
        XCTAssert(storeSpy.fetchRecordsCalled, "Calling fetchRecord(for date:) should ask the data store to fetch records")
        wait(for: [expectRecord], timeout: 0.6)
    }
    // if no records: fetchRecord should return empty today record
    // if there are records: fetchRecord should return today record from these records
    // if there are records expcept today, fetch record should return empty todays record
}
